name: Build

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Misskey commit'
        required: true
        default: 'develop'
        type: string
      tag:
        description: 'Docker image tag'
        required: false
        default: ''
        type: string
      sharkey:
        description: "It's Shark!"
        required: false
        default: false
        type: boolean

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: readme

      - name: Checkout Misskey repo
        if: ${{ ! inputs.sharkey }}
        uses: actions/checkout@v4
        with:
          repository: misskey-dev/misskey
          ref: ${{ inputs.ref }}
          path: misskey-base

      - name: Checkout Sharkey repo
        if: ${{ inputs.sharkey }}
        run: |
          git clone https://activitypub.software/TransFem-org/Sharkey.git misskey-base
          cd misskey-base
          git checkout ${{ inputs.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Apply patches
        run: |
          cd misskey-base
          bash ../patches/apply-patch.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: misskey-base
          tags: ghcr.io/outloudvi/misskey:${{ inputs.tag || inputs.ref }}
