name: Build

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Misskey commit"
        required: true
        default: "develop"
        type: string

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: readme

      - name: Checkout Misskey repo
        uses: actions/checkout@v3
        with:
          repository: misskey-dev/misskey
          ref: ${{ inputs.ref }}
          path: misskey-base

      - name: Apply patches
        run: |
          cd misskey-base
          patch Dockerfile <../patches/0001-add-nanoid-filename.patch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: misskey-base
          tags: ghcr.io/outloudvi/misskey:${{ inputs.ref }}
